### ISSUE TITLE
Missing/incorrect info: [Broken Node.js Links]

### ISSUE THREAD

**Issue by zhangwy324** [comp426-2023-spring/a01#2]
Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/a01/blob/main/README.md

#### Line number with missing or incorrect info
117, 280, 296, 300, 314, 323, 338, 348

#### What is wrong?
All Node.js links are broken

**Comment by jdmar3** [comment]
The problem is that the URLs changed sometime between when I wrote the assignment instructions and now, to include `/en/` directly after the FQDN. This is likely because the site added other languages, changed the URL structure, and did not include redirects for all the old URLs, which breaks everything. 

But, if you click on the "Learn" tab from the 404 page, all of the information is still there. Indeed you can add `/en/` to all the URLs and they will all work again.

For example, if you change line 280 from:

```
280 [Introduction to Node.js](https://nodejs.dev/learn) - Node.js
```

to:

```
280 [Introduction to Node.js](https://nodejs.dev/en/learn) - Node.js
```

the link will work. 

I have updated the template repo in https://github.com/comp426-2023-spring/a01/commit/9ded16dc25c4ebc98f69a32cd3f1ce33ada0aa6d. You can grab the new file from the template and the links will all be updated: https://raw.githubusercontent.com/comp426-2023-spring/a01/main/README.md

If you want to do that directly in your local repo to make things easy, `cd` into your local repo directory for a01 and then run:

```
curl https://raw.githubusercontent.com/comp426-2023-spring/a01/main/README.md -o README.md
```

That will replace the old version with the new one and then you can commit and push it and you'll have updated it.
