### ISSUE TITLE
Clarification needed: "The stuff that should be inside this function is all below"

### ISSUE THREAD

**Issue by kpwhit** [comp426-2023-spring/a01#8]
Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### URL of file with confusing thing
https://github.com/comp426-2023-spring/a01-kpwhit/blob/main/README.md

#### Line number of confusing thing
Comment in server.js start text that says "The stuff that should be inside this function is all below"

#### What is confusing?
Does this mean everything below should be inside the function or just some of the stuff below?

#### What do you think the confusing thing means?
I think it must mean that everything below should be inside the function, but when I try that it doesn't pass the autograder.

#### What did you read to try to understand better what is happening and solve the issue?
I read through the fs.readFile and fs.readFileSync examples as well as the http.createServer examples on the node.js website. I tried different configurations, but I'm not sure how to test it or what is causing the autograder failure.

**Comment by daqichen** [comment]
@kpwhit The function it is referring to is `server`

```
// Define a const `server` as an arrow function using http.createServer. 
...
```

The part you are reading is package import and the reasoning behind why we are importing `fs` package.

Closing issue now, hope this helps! 

**And please put issue in the MAIN repository for the future, otherwise the instructional staffs would not be notified of your issue.**
